apiVersion: apps/v1
kind: Deployment
metadata:
  name: anotherproject
spec:
  selector:
    matchLabels:
      app: anotherproject
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: anotherproject
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: almogchn/project_extension3
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
