apiVersion: apps/v3
kind: Deployment
metadata:
  name: anotherproject
spec:
  selector:
    matchLabels:
      app: hello-python3
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: anotherproject
    spec:
      containers:
      - name: anotherproject
        image: {{ .Values.image.repository }}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
