apiVersion: v1
kind: Service
metadata:
  name: anotherproject-service
spec:
  selector:
    app: anotherproject
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: {{ .Values.service.type }}
